[2025-06-01T18:14:10.724+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-01T18:14:10.745+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: log_monitoring_dag.start_spark_consumer scheduled__2025-06-01T18:05:00+00:00 [queued]>
[2025-06-01T18:14:10.757+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: log_monitoring_dag.start_spark_consumer scheduled__2025-06-01T18:05:00+00:00 [queued]>
[2025-06-01T18:14:10.758+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-06-01T18:14:10.810+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): start_spark_consumer> on 2025-06-01 18:05:00+00:00
[2025-06-01T18:14:10.818+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1049) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-01T18:14:10.820+0000] {standard_task_runner.py:72} INFO - Started process 1050 to run task
[2025-06-01T18:14:10.819+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'log_monitoring_dag', 'start_spark_consumer', 'scheduled__2025-06-01T18:05:00+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/log_monitoring_dag.py', '--cfg-path', '/tmp/tmpeztsz2uv']
[2025-06-01T18:14:10.823+0000] {standard_task_runner.py:105} INFO - Job 91: Subtask start_spark_consumer
[2025-06-01T18:14:10.902+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-01T18:14:11.016+0000] {task_command.py:467} INFO - Running <TaskInstance: log_monitoring_dag.start_spark_consumer scheduled__2025-06-01T18:05:00+00:00 [running]> on host 61a0313acf02
[2025-06-01T18:14:11.018+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-01T18:14:11.228+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='log_monitoring_dag' AIRFLOW_CTX_TASK_ID='start_spark_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-01T18:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-01T18:05:00+00:00'
[2025-06-01T18:14:11.229+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-01T18:14:11.251+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-01T18:14:11.253+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            docker run --rm             --network realtime_log_monitoring_default             -v /opt/***/app:/app             bitnami/spark:3.3.0             spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.0 /app/log_consumer.py\n        ']
[2025-06-01T18:14:11.267+0000] {subprocess.py:86} INFO - Output:
[2025-06-01T18:14:51.812+0000] {job.py:229} INFO - Heartbeat recovered after 11.65 seconds
[2025-06-01T18:15:32.609+0000] {job.py:229} INFO - Heartbeat recovered after 42.65 seconds
[2025-06-01T18:15:40.255+0000] {job.py:229} INFO - Heartbeat recovered after 27.65 seconds
[2025-06-01T18:16:24.654+0000] {job.py:229} INFO - Heartbeat recovered after 21.04 seconds
[2025-06-01T18:16:33.261+0000] {job.py:229} INFO - Heartbeat recovered after 12.28 seconds
[2025-06-01T18:17:18.348+0000] {job.py:229} INFO - Heartbeat recovered after 28.68 seconds
[2025-06-01T18:17:52.591+0000] {job.py:229} INFO - Heartbeat recovered after 35.09 seconds
[2025-06-01T18:19:22.626+0000] {job.py:229} INFO - Heartbeat recovered after 66.39 seconds
[2025-06-01T18:19:54.225+0000] {job.py:229} INFO - Heartbeat recovered after 16.91 seconds
[2025-06-01T18:20:10.537+0000] {job.py:229} INFO - Heartbeat recovered after 18.33 seconds
[2025-06-01T18:20:26.147+0000] {job.py:229} INFO - Heartbeat recovered after 19.76 seconds
[2025-06-01T18:21:34.866+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m18:21:33.74 [0m
[2025-06-01T18:21:34.881+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m18:21:34.58 [0m[1mWelcome to the Bitnami spark container[0m
[2025-06-01T18:21:34.903+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m18:21:34.58 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[2025-06-01T18:21:34.939+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m18:21:34.58 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[2025-06-01T18:21:34.952+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m18:21:34.58 [0m
[2025-06-01T18:21:38.883+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:23:42.788+0000] {job.py:229} INFO - Heartbeat recovered after 66.35 seconds
[2025-06-01T18:23:48.496+0000] {job.py:229} INFO - Heartbeat recovered after 62.73 seconds
[2025-06-01T18:26:11.236+0000] {job.py:229} INFO - Heartbeat recovered after 73.51 seconds
[2025-06-01T18:26:24.763+0000] {job.py:229} INFO - Heartbeat recovered after 77.01 seconds
[2025-06-01T18:26:34.805+0000] {job.py:229} INFO - Heartbeat recovered after 10.87 seconds
[2025-06-01T18:26:45.621+0000] {job.py:229} INFO - Heartbeat recovered after 12.48 seconds
[2025-06-01T18:27:06.427+0000] {job.py:229} INFO - Heartbeat recovered after 20.81 seconds
[2025-06-01T18:27:53.736+0000] {job.py:229} INFO - Heartbeat recovered after 48.63 seconds
[2025-06-01T18:29:30.148+0000] {job.py:229} INFO - Heartbeat recovered after 89.85 seconds
[2025-06-01T18:29:53.389+0000] {job.py:229} INFO - Heartbeat recovered after 94.61 seconds
[2025-06-01T18:30:06.707+0000] {job.py:229} INFO - Heartbeat recovered after 22.91 seconds
[2025-06-01T18:30:32.191+0000] {job.py:229} INFO - Heartbeat recovered after 13.02 seconds
[2025-06-01T18:30:42.402+0000] {job.py:229} INFO - Heartbeat recovered after 12.84 seconds
[2025-06-01T18:31:05.879+0000] {job.py:229} INFO - Heartbeat recovered after 23.53 seconds
[2025-06-01T18:31:13.910+0000] {job.py:229} INFO - Heartbeat recovered after 10.52 seconds
[2025-06-01T18:33:08.755+0000] {job.py:229} INFO - Heartbeat recovered after 114.85 seconds
[2025-06-01T18:33:20.483+0000] {job.py:229} INFO - Heartbeat recovered after 116.74 seconds
[2025-06-01T18:33:43.324+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/opt/bitnami/spark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-06-01T18:33:48.222+0000] {job.py:229} INFO - Heartbeat recovered after 12.76 seconds
[2025-06-01T18:33:48.369+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /opt/bitnami/spark/.ivy2/cache
[2025-06-01T18:33:48.422+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /opt/bitnami/spark/.ivy2/jars
[2025-06-01T18:33:48.424+0000] {subprocess.py:93} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-06-01T18:33:48.425+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-ef46667c-8398-4acf-bfd5-bcfe89b2df3d;1.0
[2025-06-01T18:33:48.470+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-06-01T18:35:27.893+0000] {job.py:229} INFO - Heartbeat recovered after 100.02 seconds
[2025-06-01T18:35:54.431+0000] {job.py:229} INFO - Heartbeat recovered after 116.47 seconds
[2025-06-01T18:37:28.018+0000] {job.py:229} INFO - Heartbeat recovered after 94.64 seconds
[2025-06-01T18:37:50.326+0000] {job.py:229} INFO - Heartbeat recovered after 24.21 seconds
[2025-06-01T18:37:52.373+0000] {subprocess.py:93} INFO - You probably access the destination server through a proxy server that is not well configured.
[2025-06-01T18:37:52.849+0000] {subprocess.py:93} INFO - You probably access the destination server through a proxy server that is not well configured.
[2025-06-01T18:37:58.297+0000] {subprocess.py:93} INFO - You probably access the destination server through a proxy server that is not well configured.
[2025-06-01T18:37:58.560+0000] {subprocess.py:93} INFO - You probably access the destination server through a proxy server that is not well configured.
[2025-06-01T18:37:59.615+0000] {job.py:229} INFO - Heartbeat recovered after 10.56 seconds
[2025-06-01T18:37:59.329+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 247712ms :: artifacts dl 0ms
[2025-06-01T18:38:00.136+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-06-01T18:38:00.387+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-06-01T18:38:00.938+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-06-01T18:38:00.972+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-06-01T18:38:01.009+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-06-01T18:38:01.011+0000] {subprocess.py:93} INFO - 	|      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
[2025-06-01T18:38:01.012+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-06-01T18:38:01.012+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.029+0000] {subprocess.py:93} INFO - :: problems summary ::
[2025-06-01T18:38:01.030+0000] {subprocess.py:93} INFO - :::: WARNINGS
[2025-06-01T18:38:01.030+0000] {subprocess.py:93} INFO - 	Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-01T18:38:01.071+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.085+0000] {subprocess.py:93} INFO - 	Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-01T18:38:01.189+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.190+0000] {subprocess.py:93} INFO - 	Host repos.spark-packages.org not found. url=https://repos.spark-packages.org/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-01T18:38:01.191+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.191+0000] {subprocess.py:93} INFO - 	Host repos.spark-packages.org not found. url=https://repos.spark-packages.org/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-01T18:38:01.211+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.212+0000] {subprocess.py:93} INFO - 		module not found: org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0
[2025-06-01T18:38:01.242+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.297+0000] {subprocess.py:93} INFO - 	==== local-m2-cache: tried
[2025-06-01T18:38:01.298+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.298+0000] {subprocess.py:93} INFO - 	  file:/opt/bitnami/spark/.m2/repository/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-01T18:38:01.299+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.299+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0!spark-sql-kafka-0-10_2.12.jar:
[2025-06-01T18:38:01.300+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.300+0000] {subprocess.py:93} INFO - 	  file:/opt/bitnami/spark/.m2/repository/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-01T18:38:01.300+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.301+0000] {subprocess.py:93} INFO - 	==== local-ivy-cache: tried
[2025-06-01T18:38:01.302+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.302+0000] {subprocess.py:93} INFO - 	  /opt/bitnami/spark/.ivy2/local/org.apache.spark/spark-sql-kafka-0-10_2.12/3.2.0/ivys/ivy.xml
[2025-06-01T18:38:01.303+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.304+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0!spark-sql-kafka-0-10_2.12.jar:
[2025-06-01T18:38:01.305+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.305+0000] {subprocess.py:93} INFO - 	  /opt/bitnami/spark/.ivy2/local/org.apache.spark/spark-sql-kafka-0-10_2.12/3.2.0/jars/spark-sql-kafka-0-10_2.12.jar
[2025-06-01T18:38:01.306+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.306+0000] {subprocess.py:93} INFO - 	==== central: tried
[2025-06-01T18:38:01.307+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.339+0000] {subprocess.py:93} INFO - 	  https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-01T18:38:01.340+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.342+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0!spark-sql-kafka-0-10_2.12.jar:
[2025-06-01T18:38:01.348+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.349+0000] {subprocess.py:93} INFO - 	  https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-01T18:38:01.397+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.397+0000] {subprocess.py:93} INFO - 	==== spark-packages: tried
[2025-06-01T18:38:01.763+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.763+0000] {subprocess.py:93} INFO - 	  https://repos.spark-packages.org/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-01T18:38:01.764+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.764+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0!spark-sql-kafka-0-10_2.12.jar:
[2025-06-01T18:38:01.765+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.766+0000] {subprocess.py:93} INFO - 	  https://repos.spark-packages.org/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-01T18:38:01.768+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.769+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-06-01T18:38:01.769+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.770+0000] {subprocess.py:93} INFO - 		::          UNRESOLVED DEPENDENCIES         ::
[2025-06-01T18:38:01.771+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.771+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-06-01T18:38:01.772+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.772+0000] {subprocess.py:93} INFO - 		:: org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0: not found
[2025-06-01T18:38:01.772+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.775+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-06-01T18:38:01.776+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.792+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.793+0000] {subprocess.py:93} INFO - 
[2025-06-01T18:38:01.793+0000] {subprocess.py:93} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2025-06-01T18:38:01.794+0000] {subprocess.py:93} INFO - Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0: not found]
[2025-06-01T18:38:01.794+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1456)
[2025-06-01T18:38:01.794+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
[2025-06-01T18:38:01.795+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
[2025-06-01T18:38:01.795+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:901)
[2025-06-01T18:38:01.795+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
[2025-06-01T18:38:01.796+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
[2025-06-01T18:38:01.796+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2025-06-01T18:38:01.845+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2025-06-01T18:38:01.845+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2025-06-01T18:38:01.874+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-06-01T18:39:30.858+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-01T18:39:37.167+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-01T18:39:39.911+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=log_monitoring_dag, task_id=start_spark_consumer, run_id=scheduled__2025-06-01T18:05:00+00:00, execution_date=20250601T180500, start_date=20250601T181410, end_date=20250601T183939
[2025-06-01T18:39:42.751+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-01T18:39:42.889+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 91 for task start_spark_consumer (Bash command failed. The command returned a non-zero exit code 1.; 1050)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-01T18:39:43.552+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-01T18:39:47.265+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-06-01T18:39:47.300+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-01T18:39:47.475+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
