[2025-06-02T01:43:06.540+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-02T01:43:06.560+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: log_monitoring_dag.start_spark_consumer manual__2025-06-02T01:38:51.955055+00:00 [queued]>
[2025-06-02T01:43:06.570+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: log_monitoring_dag.start_spark_consumer manual__2025-06-02T01:38:51.955055+00:00 [queued]>
[2025-06-02T01:43:06.572+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-06-02T01:43:07.009+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): start_spark_consumer> on 2025-06-02 01:38:51.955055+00:00
[2025-06-02T01:43:07.016+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=712) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-02T01:43:07.018+0000] {standard_task_runner.py:72} INFO - Started process 713 to run task
[2025-06-02T01:43:07.017+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'log_monitoring_dag', 'start_spark_consumer', 'manual__2025-06-02T01:38:51.955055+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/log_monitoring_dag.py', '--cfg-path', '/tmp/tmpo44csqv5']
[2025-06-02T01:43:07.019+0000] {standard_task_runner.py:105} INFO - Job 73: Subtask start_spark_consumer
[2025-06-02T01:43:07.036+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-02T01:43:07.147+0000] {task_command.py:467} INFO - Running <TaskInstance: log_monitoring_dag.start_spark_consumer manual__2025-06-02T01:38:51.955055+00:00 [running]> on host 95af1ae74a08
[2025-06-02T01:43:07.272+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='log_monitoring_dag' AIRFLOW_CTX_TASK_ID='start_spark_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-02T01:38:51.955055+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-02T01:38:51.955055+00:00'
[2025-06-02T01:43:07.273+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-02T01:43:07.291+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-02T01:43:07.292+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            docker run --rm             --network realtime_log_monitoring_default             -v /opt/***/app:/app             bitnami/spark:3.3.0             spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.0 /app/log_consumer.py\n        ']
[2025-06-02T01:43:07.314+0000] {subprocess.py:86} INFO - Output:
[2025-06-02T01:43:41.367+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m01:43:41.14 [0m
[2025-06-02T01:43:41.378+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m01:43:41.36 [0m[1mWelcome to the Bitnami spark container[0m
[2025-06-02T01:43:41.383+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m01:43:41.37 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[2025-06-02T01:43:41.395+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m01:43:41.38 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[2025-06-02T01:43:41.396+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m01:43:41.39 [0m
[2025-06-02T01:43:41.948+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:44:47.780+0000] {job.py:229} INFO - Heartbeat recovered after 15.27 seconds
[2025-06-02T01:45:05.491+0000] {job.py:229} INFO - Heartbeat recovered after 19.80 seconds
[2025-06-02T01:45:19.819+0000] {job.py:229} INFO - Heartbeat recovered after 14.34 seconds
[2025-06-02T01:46:04.367+0000] {job.py:229} INFO - Heartbeat recovered after 23.64 seconds
[2025-06-02T01:46:19.266+0000] {job.py:229} INFO - Heartbeat recovered after 23.01 seconds
[2025-06-02T01:46:44.005+0000] {job.py:229} INFO - Heartbeat recovered after 16.00 seconds
[2025-06-02T01:47:44.446+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/opt/bitnami/spark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-06-02T01:47:56.764+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /opt/bitnami/spark/.ivy2/cache
[2025-06-02T01:47:56.765+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /opt/bitnami/spark/.ivy2/jars
[2025-06-02T01:47:56.818+0000] {subprocess.py:93} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-06-02T01:47:56.834+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-db2e23e5-823e-4ec8-87db-36cbc262244f;1.0
[2025-06-02T01:47:56.835+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-06-02T01:48:29.264+0000] {subprocess.py:93} INFO - You probably access the destination server through a proxy server that is not well configured.
[2025-06-02T01:48:29.613+0000] {subprocess.py:93} INFO - You probably access the destination server through a proxy server that is not well configured.
[2025-06-02T01:48:38.798+0000] {subprocess.py:93} INFO - You probably access the destination server through a proxy server that is not well configured.
[2025-06-02T01:48:38.946+0000] {subprocess.py:93} INFO - You probably access the destination server through a proxy server that is not well configured.
[2025-06-02T01:48:43.566+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 46665ms :: artifacts dl 0ms
[2025-06-02T01:48:43.719+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-06-02T01:48:43.731+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-06-02T01:48:43.951+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-06-02T01:48:43.951+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-06-02T01:48:43.952+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-06-02T01:48:43.954+0000] {subprocess.py:93} INFO - 	|      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
[2025-06-02T01:48:43.955+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-06-02T01:48:44.702+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:44.702+0000] {subprocess.py:93} INFO - :: problems summary ::
[2025-06-02T01:48:44.703+0000] {subprocess.py:93} INFO - :::: WARNINGS
[2025-06-02T01:48:44.703+0000] {subprocess.py:93} INFO - 	Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-02T01:48:44.704+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:44.704+0000] {subprocess.py:93} INFO - 	Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-02T01:48:44.704+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:44.705+0000] {subprocess.py:93} INFO - 	Host repos.spark-packages.org not found. url=https://repos.spark-packages.org/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-02T01:48:44.705+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:44.904+0000] {subprocess.py:93} INFO - 	Host repos.spark-packages.org not found. url=https://repos.spark-packages.org/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-02T01:48:44.905+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:45.301+0000] {subprocess.py:93} INFO - 		module not found: org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0
[2025-06-02T01:48:45.302+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:45.302+0000] {subprocess.py:93} INFO - 	==== local-m2-cache: tried
[2025-06-02T01:48:45.303+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:45.303+0000] {subprocess.py:93} INFO - 	  file:/opt/bitnami/spark/.m2/repository/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-02T01:48:45.304+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:45.305+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0!spark-sql-kafka-0-10_2.12.jar:
[2025-06-02T01:48:45.305+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:45.306+0000] {subprocess.py:93} INFO - 	  file:/opt/bitnami/spark/.m2/repository/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-02T01:48:45.306+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:45.306+0000] {subprocess.py:93} INFO - 	==== local-ivy-cache: tried
[2025-06-02T01:48:45.307+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:45.307+0000] {subprocess.py:93} INFO - 	  /opt/bitnami/spark/.ivy2/local/org.apache.spark/spark-sql-kafka-0-10_2.12/3.2.0/ivys/ivy.xml
[2025-06-02T01:48:45.308+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:45.308+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0!spark-sql-kafka-0-10_2.12.jar:
[2025-06-02T01:48:45.309+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:45.309+0000] {subprocess.py:93} INFO - 	  /opt/bitnami/spark/.ivy2/local/org.apache.spark/spark-sql-kafka-0-10_2.12/3.2.0/jars/spark-sql-kafka-0-10_2.12.jar
[2025-06-02T01:48:45.309+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:45.310+0000] {subprocess.py:93} INFO - 	==== central: tried
[2025-06-02T01:48:45.310+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:45.310+0000] {subprocess.py:93} INFO - 	  https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-02T01:48:45.311+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:45.311+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0!spark-sql-kafka-0-10_2.12.jar:
[2025-06-02T01:48:45.311+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:45.312+0000] {subprocess.py:93} INFO - 	  https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-02T01:48:45.312+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:45.312+0000] {subprocess.py:93} INFO - 	==== spark-packages: tried
[2025-06-02T01:48:45.313+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:45.313+0000] {subprocess.py:93} INFO - 	  https://repos.spark-packages.org/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-02T01:48:45.313+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:45.313+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0!spark-sql-kafka-0-10_2.12.jar:
[2025-06-02T01:48:45.314+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:45.314+0000] {subprocess.py:93} INFO - 	  https://repos.spark-packages.org/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-02T01:48:45.314+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:45.315+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-06-02T01:48:45.315+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:45.315+0000] {subprocess.py:93} INFO - 		::          UNRESOLVED DEPENDENCIES         ::
[2025-06-02T01:48:45.315+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:45.316+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-06-02T01:48:45.316+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:45.316+0000] {subprocess.py:93} INFO - 		:: org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0: not found
[2025-06-02T01:48:45.316+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:45.317+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-06-02T01:48:45.317+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:45.317+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:45.318+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:48:45.318+0000] {subprocess.py:93} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2025-06-02T01:48:45.318+0000] {subprocess.py:93} INFO - Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0: not found]
[2025-06-02T01:48:45.318+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1456)
[2025-06-02T01:48:45.319+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
[2025-06-02T01:48:45.319+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
[2025-06-02T01:48:45.319+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:901)
[2025-06-02T01:48:45.320+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
[2025-06-02T01:48:45.320+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
[2025-06-02T01:48:45.320+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2025-06-02T01:48:45.321+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2025-06-02T01:48:45.321+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2025-06-02T01:48:45.321+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-06-02T01:48:48.512+0000] {job.py:229} INFO - Heartbeat recovered after 11.48 seconds
[2025-06-02T01:48:53.924+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-02T01:48:54.058+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-02T01:48:54.071+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=log_monitoring_dag, task_id=start_spark_consumer, run_id=manual__2025-06-02T01:38:51.955055+00:00, execution_date=20250602T013851, start_date=20250602T014306, end_date=20250602T014854
[2025-06-02T01:48:54.640+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-02T01:48:54.641+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 73 for task start_spark_consumer (Bash command failed. The command returned a non-zero exit code 1.; 713)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-02T01:48:54.665+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-02T01:48:54.686+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-02T01:48:54.691+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
