[2025-06-02T03:08:56.164+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-02T03:08:56.184+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: log_monitoring_dag.start_spark_consumer manual__2025-06-02T01:38:51.955055+00:00 [queued]>
[2025-06-02T03:08:56.193+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: log_monitoring_dag.start_spark_consumer manual__2025-06-02T01:38:51.955055+00:00 [queued]>
[2025-06-02T03:08:56.194+0000] {taskinstance.py:2865} INFO - Starting attempt 13 of 13
[2025-06-02T03:08:56.213+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): start_spark_consumer> on 2025-06-02 01:38:51.955055+00:00
[2025-06-02T03:08:56.716+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1550) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-02T03:08:56.715+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'log_monitoring_dag', 'start_spark_consumer', 'manual__2025-06-02T01:38:51.955055+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/log_monitoring_dag.py', '--cfg-path', '/tmp/tmp3bdk1tyu']
[2025-06-02T03:08:56.718+0000] {standard_task_runner.py:72} INFO - Started process 1551 to run task
[2025-06-02T03:08:56.718+0000] {standard_task_runner.py:105} INFO - Job 83: Subtask start_spark_consumer
[2025-06-02T03:08:56.754+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-02T03:08:56.792+0000] {task_command.py:467} INFO - Running <TaskInstance: log_monitoring_dag.start_spark_consumer manual__2025-06-02T01:38:51.955055+00:00 [running]> on host 95af1ae74a08
[2025-06-02T03:08:56.874+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='log_monitoring_dag' AIRFLOW_CTX_TASK_ID='start_spark_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-02T01:38:51.955055+00:00' AIRFLOW_CTX_TRY_NUMBER='13' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-02T01:38:51.955055+00:00'
[2025-06-02T03:08:56.875+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-02T03:08:56.894+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-02T03:08:56.897+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        docker run --rm         --network realtime_log_monitoring_default         -v $(pwd):/app         bitnami/spark:3.3.0         spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.0 /app/log_consumer.py\n    ']
[2025-06-02T03:08:56.905+0000] {subprocess.py:86} INFO - Output:
[2025-06-02T03:08:59.827+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m03:08:59.82 [0m
[2025-06-02T03:08:59.829+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m03:08:59.82 [0m[1mWelcome to the Bitnami spark container[0m
[2025-06-02T03:08:59.831+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m03:08:59.82 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[2025-06-02T03:08:59.833+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m03:08:59.83 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[2025-06-02T03:08:59.834+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m03:08:59.83 [0m
[2025-06-02T03:09:00.102+0000] {subprocess.py:93} INFO - 
[2025-06-02T03:09:02.639+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/opt/bitnami/spark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-06-02T03:09:02.695+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /opt/bitnami/spark/.ivy2/cache
[2025-06-02T03:09:02.695+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /opt/bitnami/spark/.ivy2/jars
[2025-06-02T03:09:02.699+0000] {subprocess.py:93} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-06-02T03:09:02.700+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-43944b3d-5c66-488c-bfa4-9e97b99f51a8;1.0
[2025-06-02T03:09:02.701+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-06-02T03:09:07.388+0000] {subprocess.py:93} INFO - 	found org.apache.spark#spark-sql-kafka-0-10_2.12;3.3.0 in central
[2025-06-02T03:09:08.088+0000] {subprocess.py:93} INFO - 	found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.3.0 in central
[2025-06-02T03:09:09.082+0000] {subprocess.py:93} INFO - 	found org.apache.kafka#kafka-clients;2.8.1 in central
[2025-06-02T03:09:09.701+0000] {subprocess.py:93} INFO - 	found org.lz4#lz4-java;1.8.0 in central
[2025-06-02T03:09:10.008+0000] {subprocess.py:93} INFO - 	found org.xerial.snappy#snappy-java;1.1.8.4 in central
[2025-06-02T03:09:12.227+0000] {subprocess.py:93} INFO - 	found org.slf4j#slf4j-api;1.7.32 in central
[2025-06-02T03:09:15.091+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-client-runtime;3.3.2 in central
[2025-06-02T03:09:16.986+0000] {subprocess.py:93} INFO - 	found org.spark-project.spark#unused;1.0.0 in central
[2025-06-02T03:09:17.599+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-client-api;3.3.2 in central
[2025-06-02T03:09:20.465+0000] {subprocess.py:93} INFO - 	found commons-logging#commons-logging;1.1.3 in central
[2025-06-02T03:09:20.773+0000] {subprocess.py:93} INFO - 	found com.google.code.findbugs#jsr305;3.0.0 in central
[2025-06-02T03:09:24.756+0000] {subprocess.py:93} INFO - 	found org.apache.commons#commons-pool2;2.11.1 in central
[2025-06-02T03:09:25.057+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.3.0/spark-sql-kafka-0-10_2.12-3.3.0.jar ...
[2025-06-02T03:09:25.681+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.apache.spark#spark-sql-kafka-0-10_2.12;3.3.0!spark-sql-kafka-0-10_2.12.jar (770ms)
[2025-06-02T03:09:25.831+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.3.0/spark-token-provider-kafka-0-10_2.12-3.3.0.jar ...
[2025-06-02T03:09:26.045+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.3.0!spark-token-provider-kafka-0-10_2.12.jar (363ms)
[2025-06-02T03:09:26.192+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/2.8.1/kafka-clients-2.8.1.jar ...
[2025-06-02T03:09:38.806+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.apache.kafka#kafka-clients;2.8.1!kafka-clients.jar (12760ms)
[2025-06-02T03:09:44.504+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar ...
[2025-06-02T03:09:44.525+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] com.google.code.findbugs#jsr305;3.0.0!jsr305.jar (3644ms)
[2025-06-02T03:09:48.756+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar ...
[2025-06-02T03:10:02.457+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.apache.commons#commons-pool2;2.11.1!commons-pool2.jar (4746ms)
[2025-06-02T03:10:02.465+0000] {job.py:229} INFO - Heartbeat recovered after 17.95 seconds
[2025-06-02T03:10:07.385+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/spark-project/spark/unused/1.0.0/unused-1.0.0.jar ...
[2025-06-02T03:10:07.521+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.spark-project.spark#unused;1.0.0!unused.jar (5064ms)
[2025-06-02T03:10:07.692+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-runtime/3.3.2/hadoop-client-runtime-3.3.2.jar ...
[2025-06-02T03:25:37.288+0000] {job.py:229} INFO - Heartbeat recovered after 907.52 seconds
[2025-06-02T03:25:43.314+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar ...
[2025-06-02T03:25:46.418+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.lz4#lz4-java;1.8.0!lz4-java.jar (5117ms)
[2025-06-02T03:25:46.557+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.8.4/snappy-java-1.1.8.4.jar ...
[2025-06-02T03:25:47.370+0000] {job.py:229} INFO - Heartbeat recovered after 11.12 seconds
[2025-06-02T03:25:51.654+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.xerial.snappy#snappy-java;1.1.8.4!snappy-java.jar(bundle) (5236ms)
[2025-06-02T03:25:52.202+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar ...
[2025-06-02T03:25:52.607+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.slf4j#slf4j-api;1.7.32!slf4j-api.jar (949ms)
[2025-06-02T03:25:52.823+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-api/3.3.2/hadoop-client-api-3.3.2.jar ...
[2025-06-02T10:03:04.122+0000] {job.py:229} INFO - Heartbeat recovered after 23804.07 seconds
[2025-06-02T10:03:05.014+0000] {local_task_job_runner.py:228} ERROR - Heartbeat time limit exceeded!
[2025-06-02T10:03:05.521+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-06-02T10:03:21.841+0000] {subprocess.py:93} INFO - You probably access the destination server through a proxy server that is not well configured.
[2025-06-02T10:03:22.636+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 22210ms :: artifacts dl 24836923ms
[2025-06-02T10:03:23.228+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-06-02T10:03:24.263+0000] {subprocess.py:93} INFO - 	com.google.code.findbugs#jsr305;3.0.0 from central in [default]
[2025-06-02T10:03:24.467+0000] {subprocess.py:93} INFO - 	commons-logging#commons-logging;1.1.3 from central in [default]
[2025-06-02T10:03:25.497+0000] {subprocess.py:93} INFO - 	org.apache.commons#commons-pool2;2.11.1 from central in [default]
[2025-06-02T10:03:25.706+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-client-api;3.3.2 from central in [default]
[2025-06-02T10:03:26.198+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-client-runtime;3.3.2 from central in [default]
[2025-06-02T10:03:26.208+0000] {subprocess.py:93} INFO - 	org.apache.kafka#kafka-clients;2.8.1 from central in [default]
[2025-06-02T10:03:26.808+0000] {subprocess.py:93} INFO - 	org.apache.spark#spark-sql-kafka-0-10_2.12;3.3.0 from central in [default]
[2025-06-02T10:03:26.881+0000] {subprocess.py:93} INFO - 	org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.3.0 from central in [default]
[2025-06-02T10:03:26.881+0000] {subprocess.py:93} INFO - 	org.lz4#lz4-java;1.8.0 from central in [default]
[2025-06-02T10:03:27.259+0000] {subprocess.py:93} INFO - 	org.slf4j#slf4j-api;1.7.32 from central in [default]
[2025-06-02T10:03:27.261+0000] {subprocess.py:93} INFO - 	org.spark-project.spark#unused;1.0.0 from central in [default]
[2025-06-02T10:03:27.264+0000] {subprocess.py:93} INFO - 	org.xerial.snappy#snappy-java;1.1.8.4 from central in [default]
[2025-06-02T10:03:27.266+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-06-02T10:03:27.267+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-06-02T10:03:27.268+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-06-02T10:03:27.272+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-06-02T10:03:27.274+0000] {subprocess.py:93} INFO - 	|      default     |   12  |   12  |   12  |   0   ||   12  |   9   |
[2025-06-02T10:03:27.275+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-06-02T10:03:27.279+0000] {subprocess.py:93} INFO - 
[2025-06-02T10:03:27.280+0000] {subprocess.py:93} INFO - :: problems summary ::
[2025-06-02T10:03:27.281+0000] {subprocess.py:93} INFO - :::: WARNINGS
[2025-06-02T10:03:27.282+0000] {subprocess.py:93} INFO - 		[FAILED     ] org.apache.hadoop#hadoop-client-runtime;3.3.2!hadoop-client-runtime.jar: Downloaded file size (15950722) doesn't match expected Content Length (30498151) for https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-runtime/3.3.2/hadoop-client-runtime-3.3.2.jar. Please retry. (933776ms)
[2025-06-02T10:03:27.283+0000] {subprocess.py:93} INFO - 
[2025-06-02T10:03:27.287+0000] {subprocess.py:93} INFO - 		[FAILED     ] org.apache.hadoop#hadoop-client-runtime;3.3.2!hadoop-client-runtime.jar: Downloaded file size (15950722) doesn't match expected Content Length (30498151) for https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-runtime/3.3.2/hadoop-client-runtime-3.3.2.jar. Please retry. (933776ms)
[2025-06-02T10:03:27.288+0000] {subprocess.py:93} INFO - 
[2025-06-02T10:03:27.289+0000] {subprocess.py:93} INFO - 	==== central: tried
[2025-06-02T10:03:27.290+0000] {subprocess.py:93} INFO - 
[2025-06-02T10:03:27.291+0000] {subprocess.py:93} INFO - 	  https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-runtime/3.3.2/hadoop-client-runtime-3.3.2.jar
[2025-06-02T10:03:27.292+0000] {subprocess.py:93} INFO - 
[2025-06-02T10:03:27.293+0000] {subprocess.py:93} INFO - 		[FAILED     ] org.apache.hadoop#hadoop-client-api;3.3.2!hadoop-client-api.jar: Downloaded file size (3764032) doesn't match expected Content Length (19458502) for https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-api/3.3.2/hadoop-client-api-3.3.2.jar. Please retry. (23848591ms)
[2025-06-02T10:03:27.295+0000] {subprocess.py:93} INFO - 
[2025-06-02T10:03:27.295+0000] {subprocess.py:93} INFO - 		[FAILED     ] org.apache.hadoop#hadoop-client-api;3.3.2!hadoop-client-api.jar: Downloaded file size (3764032) doesn't match expected Content Length (19458502) for https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-api/3.3.2/hadoop-client-api-3.3.2.jar. Please retry. (23848591ms)
[2025-06-02T10:03:27.296+0000] {subprocess.py:93} INFO - 
[2025-06-02T10:03:27.297+0000] {subprocess.py:93} INFO - 	==== central: tried
[2025-06-02T10:03:27.297+0000] {subprocess.py:93} INFO - 
[2025-06-02T10:03:27.299+0000] {subprocess.py:93} INFO - 	  https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-api/3.3.2/hadoop-client-api-3.3.2.jar
[2025-06-02T10:03:27.299+0000] {subprocess.py:93} INFO - 
[2025-06-02T10:03:27.300+0000] {subprocess.py:93} INFO - 	Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[2025-06-02T10:03:27.301+0000] {subprocess.py:93} INFO - 
[2025-06-02T10:03:27.302+0000] {subprocess.py:93} INFO - 		[NOT FOUND  ] commons-logging#commons-logging;1.1.3!commons-logging.jar (632ms)
[2025-06-02T10:03:27.302+0000] {subprocess.py:93} INFO - 
[2025-06-02T10:03:27.303+0000] {subprocess.py:93} INFO - 	==== central: tried
[2025-06-02T10:03:27.305+0000] {subprocess.py:93} INFO - 
[2025-06-02T10:03:27.305+0000] {subprocess.py:93} INFO - 	  https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[2025-06-02T10:03:27.306+0000] {subprocess.py:93} INFO - 
[2025-06-02T10:03:27.306+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-06-02T10:03:27.307+0000] {subprocess.py:93} INFO - 
[2025-06-02T10:03:27.307+0000] {subprocess.py:93} INFO - 		::              FAILED DOWNLOADS            ::
[2025-06-02T10:03:27.308+0000] {subprocess.py:93} INFO - 
[2025-06-02T10:03:27.308+0000] {subprocess.py:93} INFO - 		:: ^ see resolution messages for details  ^ ::
[2025-06-02T10:03:27.309+0000] {subprocess.py:93} INFO - 
[2025-06-02T10:03:27.309+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-06-02T10:03:27.310+0000] {subprocess.py:93} INFO - 
[2025-06-02T10:03:27.310+0000] {subprocess.py:93} INFO - 		:: org.apache.hadoop#hadoop-client-runtime;3.3.2!hadoop-client-runtime.jar
[2025-06-02T10:03:27.311+0000] {subprocess.py:93} INFO - 
[2025-06-02T10:03:27.311+0000] {subprocess.py:93} INFO - 		:: org.apache.hadoop#hadoop-client-api;3.3.2!hadoop-client-api.jar
[2025-06-02T10:03:27.312+0000] {subprocess.py:93} INFO - 
[2025-06-02T10:03:27.312+0000] {subprocess.py:93} INFO - 		:: commons-logging#commons-logging;1.1.3!commons-logging.jar
[2025-06-02T10:03:27.312+0000] {subprocess.py:93} INFO - 
[2025-06-02T10:03:27.313+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-06-02T10:03:27.313+0000] {subprocess.py:93} INFO - 
[2025-06-02T10:03:27.313+0000] {subprocess.py:93} INFO - 
[2025-06-02T10:03:27.342+0000] {subprocess.py:93} INFO - 
[2025-06-02T10:03:27.345+0000] {subprocess.py:93} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2025-06-02T10:03:27.348+0000] {subprocess.py:93} INFO - Exception in thread "main" java.lang.RuntimeException: [download failed: org.apache.hadoop#hadoop-client-runtime;3.3.2!hadoop-client-runtime.jar, download failed: org.apache.hadoop#hadoop-client-api;3.3.2!hadoop-client-api.jar, download failed: commons-logging#commons-logging;1.1.3!commons-logging.jar]
[2025-06-02T10:03:27.348+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1456)
[2025-06-02T10:03:27.349+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
[2025-06-02T10:03:27.349+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
[2025-06-02T10:03:27.349+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:901)
[2025-06-02T10:03:27.350+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
[2025-06-02T10:03:27.350+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
[2025-06-02T10:03:27.351+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2025-06-02T10:03:27.351+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2025-06-02T10:03:27.351+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2025-06-02T10:03:27.352+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-06-02T10:03:30.671+0000] {process_utils.py:132} INFO - Sending 15 to group 1551. PIDs of all processes in the group: [1553, 1555, 1551]
[2025-06-02T10:03:30.672+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1551
[2025-06-02T10:03:30.674+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-02T10:03:30.674+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-06-02T10:03:30.801+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 240, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-06-02T10:03:33.660+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=log_monitoring_dag, task_id=start_spark_consumer, run_id=manual__2025-06-02T01:38:51.955055+00:00, execution_date=20250602T013851, start_date=20250602T030856, end_date=20250602T100333
[2025-06-02T10:03:35.422+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-02T10:03:38.591+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1551, status='terminated', exitcode=2, started='03:08:56') (1551) terminated with exit code 2
[2025-06-02T10:03:41.140+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1553, status='terminated', started='03:08:56') (1553) terminated with exit code None
[2025-06-02T10:03:41.609+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-06-02T10:04:24.180+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1555, status='terminated', started='03:08:56') (1555) terminated with exit code None
