[2025-06-01T00:13:50.330+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-01T00:13:52.165+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: log_monitoring_dag.start_spark_consumer scheduled__2025-05-31T23:50:00+00:00 [queued]>
[2025-06-01T00:13:53.091+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: log_monitoring_dag.start_spark_consumer scheduled__2025-05-31T23:50:00+00:00 [queued]>
[2025-06-01T00:13:53.184+0000] {taskinstance.py:2865} INFO - Starting attempt 5 of 6
[2025-06-01T00:13:57.255+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): start_spark_consumer> on 2025-05-31 23:50:00+00:00
[2025-06-01T00:13:58.050+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=646) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-01T00:13:58.051+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'log_monitoring_dag', 'start_spark_consumer', 'scheduled__2025-05-31T23:50:00+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/log_monitoring_dag.py', '--cfg-path', '/tmp/tmpy8mv4a_y']
[2025-06-01T00:13:58.053+0000] {standard_task_runner.py:72} INFO - Started process 670 to run task
[2025-06-01T00:13:58.054+0000] {standard_task_runner.py:105} INFO - Job 107: Subtask start_spark_consumer
[2025-06-01T00:14:01.988+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-01T00:14:09.938+0000] {task_command.py:467} INFO - Running <TaskInstance: log_monitoring_dag.start_spark_consumer scheduled__2025-05-31T23:50:00+00:00 [running]> on host 4f4c6676a48d
[2025-06-01T00:14:10.277+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-01T00:14:12.821+0000] {job.py:229} INFO - Heartbeat recovered after 105.08 seconds
[2025-06-01T11:20:41.895+0000] {job.py:229} INFO - Heartbeat recovered after 39986.31 seconds
[2025-06-01T11:22:20.715+0000] {local_task_job_runner.py:228} ERROR - Heartbeat time limit exceeded!
[2025-06-01T11:22:22.703+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-06-01T11:22:24.016+0000] {process_utils.py:132} INFO - Sending 15 to group 670. PIDs of all processes in the group: [670]
[2025-06-01T11:22:25.132+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 670
[2025-06-01T11:22:25.894+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-01T11:22:27.519+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-06-01T11:22:59.999+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3111, in _execute_task_with_callbacks
    jinja_env = dag.get_template_env()
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 1819, in get_template_env
    env = airflow.templates.SandboxedEnvironment(**jinja_env_options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/templates.py", line 31, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/sandbox.py", line 254, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 294, in __init__
    def __init__(
    
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-06-01T11:23:27.488+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=log_monitoring_dag, task_id=start_spark_consumer, run_id=scheduled__2025-05-31T23:50:00+00:00, execution_date=20250531T235000, start_date=20250601T001352, end_date=20250601T112325
[2025-06-01T11:23:24.783+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=670, name='airflow task ru', status='running', started='00:13:57') did not respond to SIGTERM. Trying SIGKILL
[2025-06-01T11:23:32.083+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 670
[2025-06-01T11:23:36.543+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=670, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='00:13:57') (670) terminated with exit code -9
[2025-06-01T11:23:39.193+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-06-01T11:23:39.611+0000] {standard_task_runner.py:190} ERROR - ('Job 107 was killed before it finished (likely due to running out of memory)', 'For more information, see https://***.apache.org/docs/apache-***/stable/troubleshooting.html#LocalTaskJob-killed')
