[2025-06-01T21:07:41.353+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-01T21:07:45.449+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: log_monitoring_dag.start_spark_consumer scheduled__2025-06-01T18:40:00+00:00 [queued]>
[2025-06-01T21:07:53.006+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: log_monitoring_dag.start_spark_consumer scheduled__2025-06-01T18:40:00+00:00 [queued]>
[2025-06-01T21:08:08.944+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-06-01T21:08:08.968+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): start_spark_consumer> on 2025-06-01 18:40:00+00:00
[2025-06-01T21:08:09.390+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=476) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-01T21:08:09.480+0000] {standard_task_runner.py:72} INFO - Started process 508 to run task
[2025-06-01T21:08:09.393+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'log_monitoring_dag', 'start_spark_consumer', 'scheduled__2025-06-01T18:40:00+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/log_monitoring_dag.py', '--cfg-path', '/tmp/tmpkw9dikpr']
[2025-06-01T21:08:09.620+0000] {standard_task_runner.py:105} INFO - Job 169: Subtask start_spark_consumer
[2025-06-01T21:08:14.642+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-01T21:08:17.456+0000] {job.py:229} INFO - Heartbeat recovered after 45.71 seconds
[2025-06-01T21:08:25.497+0000] {task_command.py:467} INFO - Running <TaskInstance: log_monitoring_dag.start_spark_consumer scheduled__2025-06-01T18:40:00+00:00 [running]> on host 61a0313acf02
[2025-06-01T21:08:26.120+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-01T21:08:28.116+0000] {job.py:229} INFO - Heartbeat recovered after 11.67 seconds
[2025-06-01T21:08:28.826+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='log_monitoring_dag' AIRFLOW_CTX_TASK_ID='start_spark_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-01T18:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-01T18:40:00+00:00'
[2025-06-01T21:08:29.231+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-01T21:08:29.618+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-01T21:08:30.073+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            docker run --rm             --network realtime_log_monitoring_default             -v /opt/***/app:/app             bitnami/spark:3.3.0             spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.0 /app/log_consumer.py\n        ']
[2025-06-01T21:08:30.085+0000] {subprocess.py:86} INFO - Output:
[2025-06-01T21:08:43.088+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m21:08:43.04 [0m
[2025-06-01T21:08:43.089+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m21:08:43.08 [0m[1mWelcome to the Bitnami spark container[0m
[2025-06-01T21:08:43.091+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m21:08:43.08 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[2025-06-01T21:08:43.093+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m21:08:43.09 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[2025-06-01T21:08:43.094+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m21:08:43.09 [0m
[2025-06-01T21:08:43.110+0000] {subprocess.py:93} INFO - 
[2025-06-01T21:08:51.095+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/opt/bitnami/spark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-06-01T21:08:51.365+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /opt/bitnami/spark/.ivy2/cache
[2025-06-01T21:08:51.373+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /opt/bitnami/spark/.ivy2/jars
[2025-06-01T21:08:51.374+0000] {subprocess.py:93} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-06-01T21:08:51.374+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-15d1587d-9b51-4043-8af7-22d6565d2c6e;1.0
[2025-06-01T21:08:51.375+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-06-01T21:08:57.771+0000] {subprocess.py:93} INFO - 	found org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0 in central
[2025-06-01T21:08:58.909+0000] {subprocess.py:93} INFO - 	found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.2.0 in central
[2025-06-01T21:08:59.733+0000] {subprocess.py:93} INFO - 	found org.apache.kafka#kafka-clients;2.8.0 in central
[2025-06-01T21:09:03.586+0000] {subprocess.py:93} INFO - 	found org.lz4#lz4-java;1.7.1 in central
[2025-06-01T21:09:06.424+0000] {subprocess.py:93} INFO - 	found org.xerial.snappy#snappy-java;1.1.8.4 in central
[2025-06-01T21:09:11.232+0000] {subprocess.py:93} INFO - 	found org.slf4j#slf4j-api;1.7.30 in central
[2025-06-01T21:09:14.542+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-client-runtime;3.3.1 in central
[2025-06-01T21:09:15.709+0000] {subprocess.py:93} INFO - 	found org.spark-project.spark#unused;1.0.0 in central
[2025-06-01T21:09:16.339+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-client-api;3.3.1 in central
[2025-06-01T21:09:19.049+0000] {subprocess.py:93} INFO - 	found org.apache.htrace#htrace-core4;4.1.0-incubating in central
[2025-06-01T21:09:23.391+0000] {subprocess.py:93} INFO - 	found commons-logging#commons-logging;1.1.3 in central
[2025-06-01T21:09:23.681+0000] {subprocess.py:93} INFO - 	found com.google.code.findbugs#jsr305;3.0.0 in central
[2025-06-01T21:09:28.237+0000] {subprocess.py:93} INFO - 	found org.apache.commons#commons-pool2;2.6.2 in central
[2025-06-01T21:09:28.381+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar ...
[2025-06-01T21:09:33.346+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0!spark-sql-kafka-0-10_2.12.jar (5085ms)
[2025-06-01T21:09:33.472+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.2.0/spark-token-provider-kafka-0-10_2.12-3.2.0.jar ...
[2025-06-01T21:09:33.916+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.2.0!spark-token-provider-kafka-0-10_2.12.jar (578ms)
[2025-06-01T21:09:34.065+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/2.8.0/kafka-clients-2.8.0.jar ...
[2025-06-01T21:09:46.824+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.apache.kafka#kafka-clients;2.8.0!kafka-clients.jar (12870ms)
[2025-06-01T21:09:47.228+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar ...
[2025-06-01T21:09:47.870+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] com.google.code.findbugs#jsr305;3.0.0!jsr305.jar (1083ms)
[2025-06-01T21:09:48.004+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.6.2/commons-pool2-2.6.2.jar ...
[2025-06-01T21:09:48.470+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.apache.commons#commons-pool2;2.6.2!commons-pool2.jar (600ms)
[2025-06-01T21:09:48.763+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/spark-project/spark/unused/1.0.0/unused-1.0.0.jar ...
[2025-06-01T21:09:48.764+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.spark-project.spark#unused;1.0.0!unused.jar (281ms)
[2025-06-01T21:09:48.886+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-runtime/3.3.1/hadoop-client-runtime-3.3.1.jar ...
[2025-06-01T21:10:16.936+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.apache.hadoop#hadoop-client-runtime;3.3.1!hadoop-client-runtime.jar (28076ms)
[2025-06-01T21:10:17.014+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/lz4/lz4-java/1.7.1/lz4-java-1.7.1.jar ...
[2025-06-01T21:10:17.523+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.lz4#lz4-java;1.7.1!lz4-java.jar (692ms)
[2025-06-01T21:10:17.808+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.8.4/snappy-java-1.1.8.4.jar ...
[2025-06-01T21:10:19.092+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.xerial.snappy#snappy-java;1.1.8.4!snappy-java.jar(bundle) (1570ms)
[2025-06-01T21:10:19.224+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar ...
[2025-06-01T21:10:19.378+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.slf4j#slf4j-api;1.7.30!slf4j-api.jar (286ms)
[2025-06-01T21:10:19.533+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-api/3.3.1/hadoop-client-api-3.3.1.jar ...
[2025-06-01T21:11:08.572+0000] {job.py:229} INFO - Heartbeat recovered after 44.56 seconds
[2025-06-01T21:11:08.577+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.apache.hadoop#hadoop-client-api;3.3.1!hadoop-client-api.jar (49195ms)
[2025-06-01T21:11:08.715+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/apache/htrace/htrace-core4/4.1.0-incubating/htrace-core4-4.1.0-incubating.jar ...
[2025-06-01T21:11:09.817+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.apache.htrace#htrace-core4;4.1.0-incubating!htrace-core4.jar (1241ms)
[2025-06-01T21:11:10.256+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar ...
[2025-06-01T21:11:10.418+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] commons-logging#commons-logging;1.1.3!commons-logging.jar (295ms)
[2025-06-01T21:11:10.419+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 36877ms :: artifacts dl 102172ms
[2025-06-01T21:11:10.420+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-06-01T21:11:10.420+0000] {subprocess.py:93} INFO - 	com.google.code.findbugs#jsr305;3.0.0 from central in [default]
[2025-06-01T21:11:10.421+0000] {subprocess.py:93} INFO - 	commons-logging#commons-logging;1.1.3 from central in [default]
[2025-06-01T21:11:10.421+0000] {subprocess.py:93} INFO - 	org.apache.commons#commons-pool2;2.6.2 from central in [default]
[2025-06-01T21:11:10.421+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-client-api;3.3.1 from central in [default]
[2025-06-01T21:11:10.421+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-client-runtime;3.3.1 from central in [default]
[2025-06-01T21:11:10.422+0000] {subprocess.py:93} INFO - 	org.apache.htrace#htrace-core4;4.1.0-incubating from central in [default]
[2025-06-01T21:11:10.422+0000] {subprocess.py:93} INFO - 	org.apache.kafka#kafka-clients;2.8.0 from central in [default]
[2025-06-01T21:11:10.422+0000] {subprocess.py:93} INFO - 	org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0 from central in [default]
[2025-06-01T21:11:10.423+0000] {subprocess.py:93} INFO - 	org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.2.0 from central in [default]
[2025-06-01T21:11:10.423+0000] {subprocess.py:93} INFO - 	org.lz4#lz4-java;1.7.1 from central in [default]
[2025-06-01T21:11:10.423+0000] {subprocess.py:93} INFO - 	org.slf4j#slf4j-api;1.7.30 from central in [default]
[2025-06-01T21:11:10.424+0000] {subprocess.py:93} INFO - 	org.spark-project.spark#unused;1.0.0 from central in [default]
[2025-06-01T21:11:10.424+0000] {subprocess.py:93} INFO - 	org.xerial.snappy#snappy-java;1.1.8.4 from central in [default]
[2025-06-01T21:11:10.424+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-06-01T21:11:10.424+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-06-01T21:11:10.425+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-06-01T21:11:10.425+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-06-01T21:11:10.425+0000] {subprocess.py:93} INFO - 	|      default     |   13  |   13  |   13  |   0   ||   13  |   13  |
[2025-06-01T21:11:10.426+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-06-01T21:12:01.838+0000] {job.py:229} INFO - Heartbeat recovered after 56.22 seconds
[2025-06-01T21:12:02.262+0000] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-15d1587d-9b51-4043-8af7-22d6565d2c6e
[2025-06-01T21:12:02.454+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-06-01T21:12:02.702+0000] {subprocess.py:93} INFO - 	13 artifacts copied, 0 already retrieved (59181kB/636ms)
[2025-06-01T21:12:04.946+0000] {subprocess.py:93} INFO - 25/06/01 21:12:04 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-06-01T21:12:07.902+0000] {subprocess.py:93} INFO - python3: can't open file '/app/log_consumer.py': [Errno 2] No such file or directory
[2025-06-01T21:12:07.903+0000] {subprocess.py:93} INFO - 25/06/01 21:12:07 INFO ShutdownHookManager: Shutdown hook called
[2025-06-01T21:12:07.906+0000] {subprocess.py:93} INFO - 25/06/01 21:12:07 INFO ShutdownHookManager: Deleting directory /tmp/spark-d67ece8e-6bc8-4b08-8122-7bcebb671095
[2025-06-01T21:12:20.870+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-06-01T21:12:21.759+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-06-01T21:12:22.356+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=log_monitoring_dag, task_id=start_spark_consumer, run_id=scheduled__2025-06-01T18:40:00+00:00, execution_date=20250601T184000, start_date=20250601T210745, end_date=20250601T211222
[2025-06-01T21:13:12.967+0000] {job.py:229} INFO - Heartbeat recovered after 10.84 seconds
[2025-06-01T21:13:23.206+0000] {job.py:229} INFO - Heartbeat recovered after 11.84 seconds
[2025-06-01T21:14:26.868+0000] {job.py:229} INFO - Heartbeat recovered after 50.84 seconds
[2025-06-01T21:14:35.710+0000] {job.py:229} INFO - Heartbeat recovered after 52.60 seconds
[2025-06-01T21:17:10.565+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-01T21:17:13.432+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 169 for task start_spark_consumer (Bash command failed. The command returned a non-zero exit code 2.; 508)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-06-01T21:17:15.362+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-01T21:17:16.967+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-06-01T21:17:23.009+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-01T21:17:23.604+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
