[2025-06-02T01:22:46.278+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-02T01:22:48.993+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: log_monitoring_dag.start_spark_consumer scheduled__2025-06-02T00:55:00+00:00 [queued]>
[2025-06-02T01:22:49.543+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: log_monitoring_dag.start_spark_consumer scheduled__2025-06-02T00:55:00+00:00 [queued]>
[2025-06-02T01:22:49.544+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-06-02T01:22:51.559+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): start_spark_consumer> on 2025-06-02 00:55:00+00:00
[2025-06-02T01:23:01.406+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=508) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-02T01:23:05.871+0000] {standard_task_runner.py:72} INFO - Started process 524 to run task
[2025-06-02T01:22:58.589+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'log_monitoring_dag', 'start_spark_consumer', 'scheduled__2025-06-02T00:55:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/log_monitoring_dag.py', '--cfg-path', '/tmp/tmpy_yj1_6f']
[2025-06-02T01:23:06.927+0000] {standard_task_runner.py:105} INFO - Job 68: Subtask start_spark_consumer
[2025-06-02T01:23:15.083+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-02T01:23:15.215+0000] {task_command.py:467} INFO - Running <TaskInstance: log_monitoring_dag.start_spark_consumer scheduled__2025-06-02T00:55:00+00:00 [running]> on host 95af1ae74a08
[2025-06-02T01:23:15.217+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-02T01:23:35.456+0000] {job.py:229} INFO - Heartbeat recovered after 60.12 seconds
[2025-06-02T01:23:36.468+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='log_monitoring_dag' AIRFLOW_CTX_TASK_ID='start_spark_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-02T00:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-02T00:55:00+00:00'
[2025-06-02T01:23:36.776+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-02T01:23:43.338+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-02T01:23:43.762+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            docker run --rm             --network realtime_log_monitoring_default             -v /opt/***/app:/app             bitnami/spark:3.3.0             spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.0 /app/log_consumer.py\n        ']
[2025-06-02T01:23:43.782+0000] {subprocess.py:86} INFO - Output:
[2025-06-02T01:23:55.694+0000] {job.py:229} INFO - Heartbeat recovered after 15.17 seconds
[2025-06-02T01:24:26.300+0000] {job.py:229} INFO - Heartbeat recovered after 13.88 seconds
[2025-06-02T01:24:38.174+0000] {job.py:229} INFO - Heartbeat recovered after 12.57 seconds
[2025-06-02T01:25:26.446+0000] {job.py:229} INFO - Heartbeat recovered after 20.29 seconds
[2025-06-02T01:25:49.216+0000] {job.py:229} INFO - Heartbeat recovered after 22.97 seconds
[2025-06-02T01:26:01.309+0000] {job.py:229} INFO - Heartbeat recovered after 13.39 seconds
[2025-06-02T01:26:15.943+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m01:26:15.78 [0m
[2025-06-02T01:26:16.322+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m01:26:15.94 [0m[1mWelcome to the Bitnami spark container[0m
[2025-06-02T01:26:16.336+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m01:26:16.32 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[2025-06-02T01:26:16.336+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m01:26:16.32 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[2025-06-02T01:26:16.337+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m01:26:16.32 [0m
[2025-06-02T01:26:17.043+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:26:42.285+0000] {job.py:229} INFO - Heartbeat recovered after 12.36 seconds
[2025-06-02T01:26:52.828+0000] {job.py:229} INFO - Heartbeat recovered after 10.60 seconds
[2025-06-02T01:27:19.145+0000] {job.py:229} INFO - Heartbeat recovered after 20.31 seconds
[2025-06-02T01:27:56.854+0000] {job.py:229} INFO - Heartbeat recovered after 38.32 seconds
[2025-06-02T01:28:12.122+0000] {job.py:229} INFO - Heartbeat recovered after 15.27 seconds
[2025-06-02T01:28:38.936+0000] {job.py:229} INFO - Heartbeat recovered after 27.04 seconds
[2025-06-02T01:28:56.054+0000] {job.py:229} INFO - Heartbeat recovered after 18.35 seconds
[2025-06-02T01:29:09.434+0000] {job.py:229} INFO - Heartbeat recovered after 13.56 seconds
[2025-06-02T01:29:20.433+0000] {job.py:229} INFO - Heartbeat recovered after 11.39 seconds
[2025-06-02T01:29:53.979+0000] {job.py:229} INFO - Heartbeat recovered after 27.42 seconds
[2025-06-02T01:30:29.181+0000] {job.py:229} INFO - Heartbeat recovered after 17.73 seconds
[2025-06-02T01:30:45.243+0000] {job.py:229} INFO - Heartbeat recovered after 17.23 seconds
[2025-06-02T01:30:58.836+0000] {job.py:229} INFO - Heartbeat recovered after 14.42 seconds
[2025-06-02T01:31:13.460+0000] {job.py:229} INFO - Heartbeat recovered after 16.38 seconds
[2025-06-02T01:31:26.520+0000] {job.py:229} INFO - Heartbeat recovered after 13.40 seconds
[2025-06-02T01:31:32.752+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/opt/bitnami/spark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-06-02T01:31:37.716+0000] {job.py:229} INFO - Heartbeat recovered after 11.39 seconds
[2025-06-02T01:31:41.151+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /opt/bitnami/spark/.ivy2/cache
[2025-06-02T01:31:41.396+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /opt/bitnami/spark/.ivy2/jars
[2025-06-02T01:31:41.397+0000] {subprocess.py:93} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-06-02T01:31:41.427+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-ab1d588d-ff03-4a08-aae5-c3bbef58eeb6;1.0
[2025-06-02T01:31:41.644+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-06-02T01:32:11.967+0000] {subprocess.py:93} INFO - You probably access the destination server through a proxy server that is not well configured.
[2025-06-02T01:32:11.988+0000] {subprocess.py:93} INFO - You probably access the destination server through a proxy server that is not well configured.
[2025-06-02T01:32:17.755+0000] {job.py:229} INFO - Heartbeat recovered after 12.33 seconds
[2025-06-02T01:32:32.608+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 51452ms :: artifacts dl 0ms
[2025-06-02T01:32:32.756+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-06-02T01:32:32.757+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-06-02T01:32:32.757+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-06-02T01:32:32.758+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-06-02T01:32:33.110+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-06-02T01:32:33.111+0000] {subprocess.py:93} INFO - 	|      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
[2025-06-02T01:32:33.111+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-06-02T01:32:33.178+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.204+0000] {subprocess.py:93} INFO - :: problems summary ::
[2025-06-02T01:32:33.205+0000] {subprocess.py:93} INFO - :::: WARNINGS
[2025-06-02T01:32:33.229+0000] {subprocess.py:93} INFO - 	Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-02T01:32:33.255+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.256+0000] {subprocess.py:93} INFO - 	Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-02T01:32:33.257+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.257+0000] {subprocess.py:93} INFO - 		module not found: org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0
[2025-06-02T01:32:33.258+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.258+0000] {subprocess.py:93} INFO - 	==== local-m2-cache: tried
[2025-06-02T01:32:33.259+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.259+0000] {subprocess.py:93} INFO - 	  file:/opt/bitnami/spark/.m2/repository/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-02T01:32:33.260+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.260+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0!spark-sql-kafka-0-10_2.12.jar:
[2025-06-02T01:32:33.260+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.261+0000] {subprocess.py:93} INFO - 	  file:/opt/bitnami/spark/.m2/repository/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-02T01:32:33.278+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.279+0000] {subprocess.py:93} INFO - 	==== local-ivy-cache: tried
[2025-06-02T01:32:33.279+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.279+0000] {subprocess.py:93} INFO - 	  /opt/bitnami/spark/.ivy2/local/org.apache.spark/spark-sql-kafka-0-10_2.12/3.2.0/ivys/ivy.xml
[2025-06-02T01:32:33.280+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.280+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0!spark-sql-kafka-0-10_2.12.jar:
[2025-06-02T01:32:33.280+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.281+0000] {subprocess.py:93} INFO - 	  /opt/bitnami/spark/.ivy2/local/org.apache.spark/spark-sql-kafka-0-10_2.12/3.2.0/jars/spark-sql-kafka-0-10_2.12.jar
[2025-06-02T01:32:33.282+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.282+0000] {subprocess.py:93} INFO - 	==== central: tried
[2025-06-02T01:32:33.283+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.284+0000] {subprocess.py:93} INFO - 	  https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-02T01:32:33.284+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.285+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0!spark-sql-kafka-0-10_2.12.jar:
[2025-06-02T01:32:33.285+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.587+0000] {subprocess.py:93} INFO - 	  https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-02T01:32:33.588+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.667+0000] {subprocess.py:93} INFO - 	==== spark-packages: tried
[2025-06-02T01:32:33.669+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.671+0000] {subprocess.py:93} INFO - 	  https://repos.spark-packages.org/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-02T01:32:33.672+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.672+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0!spark-sql-kafka-0-10_2.12.jar:
[2025-06-02T01:32:33.673+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.674+0000] {subprocess.py:93} INFO - 	  https://repos.spark-packages.org/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-02T01:32:33.675+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.675+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-06-02T01:32:33.676+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.702+0000] {subprocess.py:93} INFO - 		::          UNRESOLVED DEPENDENCIES         ::
[2025-06-02T01:32:33.702+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.703+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-06-02T01:32:33.703+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.813+0000] {subprocess.py:93} INFO - 		:: org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0: not found
[2025-06-02T01:32:33.814+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.820+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-06-02T01:32:33.822+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.822+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.823+0000] {subprocess.py:93} INFO - 
[2025-06-02T01:32:33.823+0000] {subprocess.py:93} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2025-06-02T01:32:35.692+0000] {subprocess.py:93} INFO - Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0: not found]
[2025-06-02T01:32:35.693+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1456)
[2025-06-02T01:32:35.694+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
[2025-06-02T01:32:35.695+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
[2025-06-02T01:32:35.696+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:901)
[2025-06-02T01:32:35.697+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
[2025-06-02T01:32:35.697+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
[2025-06-02T01:32:35.778+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2025-06-02T01:32:35.778+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2025-06-02T01:32:35.779+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2025-06-02T01:32:35.780+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-06-02T01:32:51.693+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-02T01:33:00.680+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-02T01:33:02.805+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=log_monitoring_dag, task_id=start_spark_consumer, run_id=scheduled__2025-06-02T00:55:00+00:00, execution_date=20250602T005500, start_date=20250602T012248, end_date=20250602T013301
[2025-06-02T01:33:08.556+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-02T01:33:08.725+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 68 for task start_spark_consumer (Bash command failed. The command returned a non-zero exit code 1.; 524)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-02T01:33:09.872+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-02T01:33:13.602+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-06-02T01:33:15.812+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-02T01:33:16.666+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
