[2025-06-01T23:13:46.596+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-01T23:13:46.624+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: log_monitoring_dag.start_spark_consumer scheduled__2025-06-01T23:05:00+00:00 [queued]>
[2025-06-01T23:13:46.634+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: log_monitoring_dag.start_spark_consumer scheduled__2025-06-01T23:05:00+00:00 [queued]>
[2025-06-01T23:13:46.635+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-06-01T23:13:46.652+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): start_spark_consumer> on 2025-06-01 23:05:00+00:00
[2025-06-01T23:13:46.662+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=293) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-01T23:13:46.663+0000] {standard_task_runner.py:72} INFO - Started process 299 to run task
[2025-06-01T23:13:46.662+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'log_monitoring_dag', 'start_spark_consumer', 'scheduled__2025-06-01T23:05:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/log_monitoring_dag.py', '--cfg-path', '/tmp/tmp0l4xevlz']
[2025-06-01T23:13:46.688+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask start_spark_consumer
[2025-06-01T23:13:46.709+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-01T23:13:46.861+0000] {task_command.py:467} INFO - Running <TaskInstance: log_monitoring_dag.start_spark_consumer scheduled__2025-06-01T23:05:00+00:00 [running]> on host 2317d0480f96
[2025-06-01T23:13:46.865+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-01T23:13:47.062+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='log_monitoring_dag' AIRFLOW_CTX_TASK_ID='start_spark_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-01T23:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-01T23:05:00+00:00'
[2025-06-01T23:13:47.064+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-01T23:13:47.083+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-01T23:13:47.084+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            docker run --rm             --network realtime_log_monitoring_default             -v /opt/***/app:/app             bitnami/spark:3.3.0             spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.0 /app/log_consumer.py\n        ']
[2025-06-01T23:13:47.096+0000] {subprocess.py:86} INFO - Output:
[2025-06-01T23:13:52.184+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m23:13:52.18 [0m
[2025-06-01T23:13:52.185+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m23:13:52.18 [0m[1mWelcome to the Bitnami spark container[0m
[2025-06-01T23:13:52.187+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m23:13:52.18 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[2025-06-01T23:13:52.190+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m23:13:52.18 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[2025-06-01T23:13:52.191+0000] {subprocess.py:93} INFO - [38;5;6m [38;5;5m23:13:52.19 [0m
[2025-06-01T23:13:52.225+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:15:18.678+0000] {job.py:229} INFO - Heartbeat recovered after 18.18 seconds
[2025-06-01T23:16:06.163+0000] {job.py:229} INFO - Heartbeat recovered after 51.40 seconds
[2025-06-01T23:16:50.805+0000] {job.py:229} INFO - Heartbeat recovered after 13.98 seconds
[2025-06-01T23:17:13.402+0000] {job.py:229} INFO - Heartbeat recovered after 12.02 seconds
[2025-06-01T23:17:37.073+0000] {job.py:229} INFO - Heartbeat recovered after 24.67 seconds
[2025-06-01T23:17:55.396+0000] {job.py:229} INFO - Heartbeat recovered after 20.08 seconds
[2025-06-01T23:18:20.387+0000] {job.py:229} INFO - Heartbeat recovered after 11.10 seconds
[2025-06-01T23:18:31.565+0000] {job.py:229} INFO - Heartbeat recovered after 12.02 seconds
[2025-06-01T23:18:45.525+0000] {job.py:229} INFO - Heartbeat recovered after 14.56 seconds
[2025-06-01T23:19:02.360+0000] {job.py:229} INFO - Heartbeat recovered after 17.03 seconds
[2025-06-01T23:19:14.589+0000] {job.py:229} INFO - Heartbeat recovered after 12.44 seconds
[2025-06-01T23:20:20.248+0000] {job.py:229} INFO - Heartbeat recovered after 17.14 seconds
[2025-06-01T23:20:35.019+0000] {job.py:229} INFO - Heartbeat recovered after 16.69 seconds
[2025-06-01T23:21:36.790+0000] {job.py:229} INFO - Heartbeat recovered after 12.29 seconds
[2025-06-01T23:22:07.224+0000] {job.py:229} INFO - Heartbeat recovered after 18.24 seconds
[2025-06-01T23:22:19.196+0000] {job.py:229} INFO - Heartbeat recovered after 11.99 seconds
[2025-06-01T23:23:05.326+0000] {job.py:229} INFO - Heartbeat recovered after 46.38 seconds
[2025-06-01T23:23:15.019+0000] {job.py:229} INFO - Heartbeat recovered after 11.24 seconds
[2025-06-01T23:23:39.191+0000] {job.py:229} INFO - Heartbeat recovered after 26.11 seconds
[2025-06-01T23:23:57.311+0000] {job.py:229} INFO - Heartbeat recovered after 20.30 seconds
[2025-06-01T23:24:48.667+0000] {job.py:229} INFO - Heartbeat recovered after 44.27 seconds
[2025-06-01T23:25:29.116+0000] {job.py:229} INFO - Heartbeat recovered after 19.90 seconds
[2025-06-01T23:25:59.235+0000] {job.py:229} INFO - Heartbeat recovered after 31.22 seconds
[2025-06-01T23:26:40.049+0000] {job.py:229} INFO - Heartbeat recovered after 41.71 seconds
[2025-06-01T23:27:00.027+0000] {job.py:229} INFO - Heartbeat recovered after 11.15 seconds
[2025-06-01T23:27:35.162+0000] {job.py:229} INFO - Heartbeat recovered after 14.74 seconds
[2025-06-01T23:28:05.758+0000] {job.py:229} INFO - Heartbeat recovered after 19.78 seconds
[2025-06-01T23:28:40.721+0000] {job.py:229} INFO - Heartbeat recovered after 27.57 seconds
[2025-06-01T23:29:00.864+0000] {job.py:229} INFO - Heartbeat recovered after 20.56 seconds
[2025-06-01T23:29:30.555+0000] {job.py:229} INFO - Heartbeat recovered after 24.67 seconds
[2025-06-01T23:29:52.969+0000] {job.py:229} INFO - Heartbeat recovered after 23.71 seconds
[2025-06-01T23:30:22.034+0000] {job.py:229} INFO - Heartbeat recovered after 29.07 seconds
[2025-06-01T23:30:41.036+0000] {job.py:229} INFO - Heartbeat recovered after 21.56 seconds
[2025-06-01T23:31:26.155+0000] {job.py:229} INFO - Heartbeat recovered after 48.63 seconds
[2025-06-01T23:31:50.598+0000] {job.py:229} INFO - Heartbeat recovered after 25.89 seconds
[2025-06-01T23:32:44.703+0000] {job.py:229} INFO - Heartbeat recovered after 18.55 seconds
[2025-06-01T23:32:58.252+0000] {job.py:229} INFO - Heartbeat recovered after 13.93 seconds
[2025-06-01T23:33:06.390+0000] {job.py:229} INFO - Heartbeat recovered after 14.78 seconds
[2025-06-01T23:33:16.581+0000] {job.py:229} INFO - Heartbeat recovered after 12.66 seconds
[2025-06-01T23:33:32.408+0000] {job.py:229} INFO - Heartbeat recovered after 15.84 seconds
[2025-06-01T23:33:37.727+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/opt/bitnami/spark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-06-01T23:33:49.131+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /opt/bitnami/spark/.ivy2/cache
[2025-06-01T23:33:49.389+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /opt/bitnami/spark/.ivy2/jars
[2025-06-01T23:33:49.532+0000] {subprocess.py:93} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-06-01T23:33:49.739+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-a2bae782-54ad-403a-a957-f31250197cd0;1.0
[2025-06-01T23:33:50.035+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-06-01T23:33:54.743+0000] {subprocess.py:93} INFO - You probably access the destination server through a proxy server that is not well configured.
[2025-06-01T23:33:55.595+0000] {subprocess.py:93} INFO - You probably access the destination server through a proxy server that is not well configured.
[2025-06-01T23:34:04.179+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 28686ms :: artifacts dl 0ms
[2025-06-01T23:34:04.194+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-06-01T23:34:04.469+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-06-01T23:34:04.775+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-06-01T23:34:05.067+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-06-01T23:34:05.473+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-06-01T23:34:05.501+0000] {subprocess.py:93} INFO - 	|      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
[2025-06-01T23:34:05.501+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-06-01T23:34:05.840+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:06.024+0000] {subprocess.py:93} INFO - :: problems summary ::
[2025-06-01T23:34:06.150+0000] {subprocess.py:93} INFO - :::: WARNINGS
[2025-06-01T23:34:06.203+0000] {subprocess.py:93} INFO - 	Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-01T23:34:06.271+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:06.446+0000] {subprocess.py:93} INFO - 	Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-01T23:34:06.671+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:06.819+0000] {subprocess.py:93} INFO - 		module not found: org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0
[2025-06-01T23:34:06.837+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:06.838+0000] {subprocess.py:93} INFO - 	==== local-m2-cache: tried
[2025-06-01T23:34:06.945+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:06.945+0000] {subprocess.py:93} INFO - 	  file:/opt/bitnami/spark/.m2/repository/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-01T23:34:06.946+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:06.946+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0!spark-sql-kafka-0-10_2.12.jar:
[2025-06-01T23:34:06.947+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:07.082+0000] {subprocess.py:93} INFO - 	  file:/opt/bitnami/spark/.m2/repository/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-01T23:34:07.083+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:07.252+0000] {subprocess.py:93} INFO - 	==== local-ivy-cache: tried
[2025-06-01T23:34:07.919+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:08.014+0000] {subprocess.py:93} INFO - 	  /opt/bitnami/spark/.ivy2/local/org.apache.spark/spark-sql-kafka-0-10_2.12/3.2.0/ivys/ivy.xml
[2025-06-01T23:34:08.015+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:08.015+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0!spark-sql-kafka-0-10_2.12.jar:
[2025-06-01T23:34:08.016+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:08.053+0000] {subprocess.py:93} INFO - 	  /opt/bitnami/spark/.ivy2/local/org.apache.spark/spark-sql-kafka-0-10_2.12/3.2.0/jars/spark-sql-kafka-0-10_2.12.jar
[2025-06-01T23:34:08.199+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:08.200+0000] {subprocess.py:93} INFO - 	==== central: tried
[2025-06-01T23:34:08.200+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:08.201+0000] {subprocess.py:93} INFO - 	  https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-01T23:34:08.201+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:08.227+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0!spark-sql-kafka-0-10_2.12.jar:
[2025-06-01T23:34:08.248+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:08.249+0000] {subprocess.py:93} INFO - 	  https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-01T23:34:08.258+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:08.260+0000] {subprocess.py:93} INFO - 	==== spark-packages: tried
[2025-06-01T23:34:08.261+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:08.262+0000] {subprocess.py:93} INFO - 	  https://repos.spark-packages.org/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.pom
[2025-06-01T23:34:08.263+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:08.376+0000] {subprocess.py:93} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0!spark-sql-kafka-0-10_2.12.jar:
[2025-06-01T23:34:08.377+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:08.539+0000] {subprocess.py:93} INFO - 	  https://repos.spark-packages.org/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar
[2025-06-01T23:34:08.972+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:08.973+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-06-01T23:34:09.001+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:09.010+0000] {subprocess.py:93} INFO - 		::          UNRESOLVED DEPENDENCIES         ::
[2025-06-01T23:34:09.036+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:09.166+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-06-01T23:34:09.175+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:09.182+0000] {subprocess.py:93} INFO - 		:: org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0: not found
[2025-06-01T23:34:09.196+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:09.552+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-06-01T23:34:09.743+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:09.751+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:09.752+0000] {subprocess.py:93} INFO - 
[2025-06-01T23:34:09.753+0000] {subprocess.py:93} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2025-06-01T23:34:09.753+0000] {subprocess.py:93} INFO - Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: org.apache.spark#spark-sql-kafka-0-10_2.12;3.2.0: not found]
[2025-06-01T23:34:09.753+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1456)
[2025-06-01T23:34:10.048+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
[2025-06-01T23:34:10.049+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
[2025-06-01T23:34:10.049+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:901)
[2025-06-01T23:34:10.075+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
[2025-06-01T23:34:10.077+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
[2025-06-01T23:34:10.078+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2025-06-01T23:34:10.259+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2025-06-01T23:34:10.260+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2025-06-01T23:34:10.260+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-06-01T23:34:27.432+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-01T23:35:20.632+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-01T23:35:31.925+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=log_monitoring_dag, task_id=start_spark_consumer, run_id=scheduled__2025-06-01T23:05:00+00:00, execution_date=20250601T230500, start_date=20250601T231346, end_date=20250601T233530
[2025-06-01T23:35:37.011+0000] {job.py:229} INFO - Heartbeat recovered after 11.53 seconds
[2025-06-01T23:35:41.724+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-01T23:35:42.477+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task start_spark_consumer (Bash command failed. The command returned a non-zero exit code 1.; 299)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-01T23:35:43.956+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-01T23:35:45.448+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-06-01T23:36:05.417+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-01T23:36:05.843+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
